version: '3.8'

services:

  auth-service:
    image: vijayabout2001/blog_repo:auth-service-v1
    build:
      context: .
      target: auth-service
    # ports:
    #   - "5000:5000"
    env_file:
      - apps/auth-service/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres.ppbjlfrjhjodibijghkl:fA%3Fa2tF8NqLu9PS@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?pgbouncer=true
      - UPSTASH_REDIS_REST_URL=https://talented-dodo-136646.upstash.io
      - UPSTASH_REDIS_REST_TOKEN=gQAAAAAAAhXGAAIgcDEzZDkwN2U1ZTJlZTY0Nzk5OTcwM2VmNWYwMTM2NTQwMw
      - JWT_SECRET=supersecretjwtkeyforauth
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_SECRET=supersecretrefreshkey
      - JWT_REFRESH_EXPIRES_IN=7d

  blog-service:
    image: vijayabout2001/blog_repo:blog-service-v1
    build:
      context: .
      target: blog-service
    # ports:
    #   - "5001:5001"
    env_file:
      - apps/blog-service/.env
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb+srv://Surya:271124@backend.m0gxk.mongodb.net/?appName=Backend
      - UPSTASH_REDIS_REST_URL=https://talented-dodo-136646.upstash.io
      - UPSTASH_REDIS_REST_TOKEN=gQAAAAAAAhXGAAIgcDEzZDkwN2U1ZTJlZTY0Nzk5OTcwM2VmNWYwMTM2NTQwMw
      - JWT_SECRET=supersecretjwtkeyforauth

  web:
    image: vijayabout2001/blog_repo:web-v1
    build:
      context: .
      target: web
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - blog-service

