services:
  - type: web
    name: auth-service
    env: image
    image:
      url: docker.io/vijayabout2001/blog_repo:auth-service-v1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        fromDatabase:
          name: blog_users_db
          property: connectionString
      - key: UPSTASH_REDIS_REST_URL
        value: https://talented-dodo-136646.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: gQAAAAAAAhXGAAIgcDEzZDkwN2U1ZTJlZTY0Nzk5OTcwM2VmNWYwMTM2NTQwMw
      - key: JWT_SECRET
        value: supersecretjwtkeyforauth
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_SECRET
        value: supersecretrefreshkey
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

  - type: web
    name: blog-service
    env: image
    image:
      url: docker.io/vijayabout2001/blog_repo:blog-service-v1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: MONGO_URI
        value: mongodb+srv://Surya:271124@backend.m0gxk.mongodb.net/?appName=Backend
      - key: UPSTASH_REDIS_REST_URL
        value: https://talented-dodo-136646.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: gQAAAAAAAhXGAAIgcDEzZDkwN2U1ZTJlZTY0Nzk5OTcwM2VmNWYwMTM2NTQwMw
      - key: JWT_SECRET
        value: supersecretjwtkeyforauth

  - type: web
    name: web
    env: image
    image:
      url: docker.io/vijayabout2001/blog_repo:web-v1
    envVars:
      - key: AUTH_SERVICE_URL
        value: http://auth-service:5000
      - key: BLOG_SERVICE_URL
        value: http://blog-service:5001

databases:
  - name: blog_users_db
    databaseName: blog_users
    user: surya
